# prettier 配置。参考 https://www.prettier.cn/docs/options.html
# 行宽
# printWidth: 80
printWidth: 120
# 缩进宽度
tabWidth: 2
# 使用 Tab 代替 空格 缩进
useTabs: false
# 句末分号
semi: true
# 字符串包裹用单引号 '' 代替 双引号 "" ， JSX 中的引号会忽略此规则参考 jsxSingleQuote
# singleQuote: false
# 对象属性键名是否使用引号： "as-needed" 必要时使用； "consistent" 如果有一个使用其他的也必须使用； "preserve" 保持原样
quoteProps: "as-needed"
# JSX 中字符串包裹使用单引号 '' 代替双引号 ""
# jsxSingleQuote: false
# 尾随逗号： "es5" 的对象和数组每个属性都使用尾随逗号； "none" 对象最后一个属性省略尾随逗号； "all" 尽可能的追加尾随逗号包括 TS
trailingComma: "es5"
# 字面量对象括号间使用空格： true { a: 1 } ； false {a: 1}
bracketSpacing: true
# 多行开始标签中的 > 放在行末不另起一行（自闭标签无效） 2.4 之前使用 jsxBracketSameLine 属性
jsxBracketSameLine: false
bracketSameLine: false
# 箭头函数单参数是否使用括号 "always" 总是使用 "avoid" 禁止使用
arrowParens: "always"
# 格式化文件的范围 rangeStart 开始行 rangeEnd 结束行
# rangeStart: 0
# rangeEnd: Infinity
# 指定语言解析器
# parser: None
# 按需格式化，仅格式化带有特殊注释的文件
# requirePragma: false
# 已格式化的文件插入特殊注释
# insertPragma: false
# 无标签文本换（尤其是 markdown 文件）： "always" 溢出行宽换行； "never" 全部不换行； "preserve" 保持原样
proseWrap: "preserve"
# 行内元素空格敏感性： "css" 参考元素默认 display 确认空格敏感性； "strict" 严格执行空格敏感； "ignore" 忽略空格敏感；
htmlWhitespaceSensitivity: "css"
# 是否缩进 .vue 文件中的样式与脚本
# vueIndentScriptAndStyle: false
vueIndentScriptAndStyle: true
# 换行符 "lf" \n "crlf" \r\n "cr" \r "auto" 参考第一行
endOfLine: "lf"
# 格式化内嵌代码，如 markdown 中的 ``` "auto" 格式化 "off" 不格式化
embeddedLanguageFormatting: "auto"
